title: Audax Dnipro
email: audax.dnipro@gmail.com
description: "" # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://audax.dp.ua"

recaptcha_site_key: 6LftFb0UAAAAAFZTHBeHCHYAccJoPqFr3Qg4rgIT

# Build settings
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-sitemap

exclude:
  - .github
  - bin/

defaults:
  -
    scope:
      path: ""
      type: "brevets2021"
    values:
      layout: brevet
  -
    scope:
      path: ""
      type: "brevets2020"
    values:
      layout: brevet


collections:
  brevets2020:
    output: true
    permalink: /brevets/2020/:name
  brevets2021:
    output: true
    permalink: /brevets/2021/:name
