name: Jekyll site CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/vendor/bundle:/usr/local/bundle \
        -e JEKYLL_UID=$(id -u) \
        -e JEKYLL_GID=$(id -g) \
        jekyll/jekyll:4.0 \
        bash -c "jekyll build --trace && ls -la"
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: _site
      env:
        GITHUB_PAT: ${{ secrets.ACTIONS_PAT }}
